### ISSUE TITLE
In-place matrix operations

### ISSUE THREAD

**Issue by yongqli** [albertoruiz/hmatrix#105]
Is there a way to do in-place matrix operations such as multiply and inversion? Would that be a good idea?

**Comment by yongqli** [comment]
I'm interested in 4x4 to 5x5 matrices. I guess there's no multiplication or inversion, etc, already written? I suppose I can use unsafeMatrixToForeignPtr and do FFI -- would I need to make sure it is row major first?

**Comment by albertoruiz** [comment]
You could try a custom matrix product for 4x4 or 5x5, using ST or other available FFI tools in the devel module (see [examples/devel](https://github.com/albertoruiz/hmatrix/tree/master/examples/devel)). The row order is changed by transposes, so yes, you must take into account row order in your routines or force the order using cmat.
But do it only if this is clearly your bottleneck.
And for the inverse operation, I don't think that a custom implementation is worth the effort. And note that perhaps you don't actually need the inverse, but the solution of a linear system (perhaps in the least squares sense) which can be done in a more numerically stable way using [these functions](https://hackage.haskell.org/package/hmatrix-0.16.1.3/docs/Numeric-LinearAlgebra-HMatrix.html#g:8).

**Comment by sid-kap** [comment]
Just curious, which functions do BLAS and LAPACK have in-place versions of? Would it be a good idea to provide a Haskell ST interface to those functions?

**Comment by albertoruiz** [comment]
Many LAPACK functions work in-place, overwriting some input matrix with the result, so the pure interface with immutable arrays need data copies. There is probably not much to be gained by providing additional in-place versions of high level linear algebra functions because computing time usually dominates memory allocation and copy.

In any case, we now have in-place [matrix product](http://hackage.haskell.org/package/hmatrix-0.17.0.1/docs/Numeric-LinearAlgebra-Devel.html#v:gemmm) and other [basic operations](http://dis.um.es/~alberto/hmatrix/st.html), and other functions could be added if profiling indicates that memory allocation is the bottleneck of an algorithm.
