### ISSUE TITLE
Undescriptive LAPACK errors when NaNs are present in the matrix

### ISSUE THREAD

**Issue by udevd** [albertoruiz/hmatrix#112]
When NaNs are present in the matrix, depending on which function is used and installed LAPACK version, following error messages may appear (when invoking eigenvalues):
 ** On entry to ZGEBAL parameter number  3 had an illegal value
 ** On entry to ZGEHRD parameter number  2 had an illegal value
 ** On entry to ZHSEQR parameter number  4 had an illegal value
Which meaning I've found after few hours on the Internet --- for future users perhaps it would be better if more descriptive error message would be shown.
eigenvaluesSH 'catches' these NaNs and returns its own error (saying that matrix must be hermitian or symmetric real), but it could be changed to be a little more descriptive as well.

**Comment by albertoruiz** [comment]
It is not easy to change those messages. They are generated by auxiliary LAPACK functions in certain versions. For example, in my computer (libatlas-base) I don't get any error:

    > let m = matrix 2 [-1,4,4,1]
    > eig (sqrt m)
    (fromList [NaN :+ 0.0,NaN :+ 0.0],(2><2)
     [ NaN :+ 0.0, NaN :+ 0.0
     , NaN :+ 0.0, NaN :+ 0.0 ])

NaN's are detected in eigSH by luck, the test fails because NaN /= NaN. This particular message could be changed, but there is still the problem with eigSH' which assumes a symmetric/hermitian input matrix without any test. Checking for NaN's in all functions is not good for efficiency, although the overhead is probably small in relation to total computing time. We can think about this.

In any case you can check that the input data is ok with a simple test:

    > let x = sqrt m
    > x==x
    False
