### ISSUE TITLE
CG for symmetric matrices returns RHS

### ISSUE THREAD

**Issue by cruegge** [albertoruiz/hmatrix#137]
The CG implementation with parameter `sym = True` appears to be faulty. If I see it correctly, the initial residual is computed as `r0 = A^T rhs - A^T A x0` in `solveG` (`A` is the matrix), regardless of the `sym` parameter. But the `cg` function itself then solves the equation for `A` instead of `A^T A`, so effectively, the method solves something like `A x = A^T y` (at least for `x0 = 0`), leading to `x = y`.

**Comment by albertoruiz** [comment]
Yes, this is a big bug: `a` and `b` in `solveG` are set for the normal equations, regardless of `sym`. 
This can be fixed by passing `sym` to `solveG` and changing the defs of `a` and `b` to

    a = if sym then ma else mat . ma
    b = if sym then rawb else mat rawb

I will add a unit test for the symmetric case and push the fix as soon as possible.

Thank you very much for the bug report!
