### ISSUE TITLE
Some common operations with Numeric.LinearAlgebra.Static seem kind of difficult

### ISSUE THREAD

**Issue by samvher** [albertoruiz/hmatrix#146]
Hi Alberto,

I'm really liking hmatrix, it's very fast and I like the type checking on dimensions a lot. However, I'm trying to use it in a practical application now (a ray-tracer) and I'm running into some issues. For example, I can't seem to easily obtain the (L2) norm of a vector. I can use
     sqrt $ (v ** 2) <·> 1
but I don't even know how to type the · character so I have to copy paste it from your tutorial :)

Also, for example, I have difficulty figuring out how to flexibly change matrix sizes or update elements (e.g. I want to generate a 3x3 rotation matrix, and then expand it to 4x4 adding only a 1 in the bottom right corner to adapt to homogeneous coordinates). With the regular HMatrix module I can do this with fromBlocks but that function is not available in Static.

Do you welcome contributions to the module? Earlier I was thinking of working on a (simple) statically type-checked LA system with a LAPACK/BLAS backend but it would of course be much more effective to contribute to an existing system (even if it is still a bit experimental). So if you feel like you would actively merge pull requests I think I would enjoy spending some time on that (starting by trying to figure out a bit better how everything works and contributing to the documentation along the way). But if the module is mostly your own research playground and code contributions would cause incompatibilities, reduce agility or otherwise not be in line with your goals I'll watch it mature a bit more from a distance.

Best

**Comment by albertoruiz** [comment]
Hi Sam,

The initial goal is that the Static module provides the basic functions that require dimension checking. Any other useful function should be easily defined in terms of these. If not, we can add it to the library. (If dimension checking is not relevant in some stage of the computation we can always use "extract" and the regular interface.)

I must update the tutorial. In the next version (master branch, very soon in hackage) I have replaced most unicode symbols by normal characters, so for example you can define the L2 norm as:

    norm_2 v = sqrt (v <.> v)

Also, the "above" and "besides" operators are now === and |||. The function you mention to convert a transformation to homogeneous coordinates ("mhomog" in the tutorial) can be defined as

    toHomog m =   m   |||   col 0
                      ===
                row 0 ||| (1::L 1 1)

There is no general "fromBlocks" because if lists are used for the input we need an explicit and possibly complex type annotation for the resulting dimension, which cannot be automatically inferred at compile time. I hope that (|||) (===), together with "split", "headTail", etc., are useful primitives to build and extract matrices.

Let me know if there is any important function you think is missing, perhaps it can be easily added. I am happy to receive contributions and I merge all reasonable pull requests. (If I am not sure about a particular contribution it can be first tested in a feature branch or fork.)

In case you take a look at the source code, note that many internal modules have recently been simplified and refactored but there are two important changes that remain to be done. Constant and diagonal matrices are not yet efficiently represented in the regular interface. They are always explicitly expanded, which is not very efficient. In the static interface these special matrices are stored in a compact form and only expanded when really needed. For instance, a matrix product involving a diagonal matrix is implemented as a scaling of rows or columns. But this compact representation is "implicit" at the moment, which can be very confusing for people looking into the code. An appropriate data type will be introduced in the next version.

Thanks for your message!

**Comment by samvher** [comment]
Awesome response! Thanks a lot. I will grab the master branch, use the code and see if I run into anything. The functions you describe seem completely sufficient, and very readable, solutions for the issues I encountered.

**Comment by samvher** [comment]
Hello Alberto,

I "finished" my raytracer (or let's say I got it into a working state which will do for now), and thought I would get back to you about my experiences with the hmatrix static library.

Overall the code was quite usable, it was kind of fun to learn how to work with it. I couldn't say with certainty that the compile-time dimension checking saved me from bugs, but basically all my vectors were of length 3 or 4 and matrices of 3x3 or 4x4 so maybe there is just not much to be gained in this use case (I think when working with more diverse matrix sizes there is definitely a gain).

I found the matrix composition with `|||` and `===` quite clear and easy to work with. `split` and `headTail` were less convenient, it was quite complicated to index into my vectors/matrices, but I realize that the type system might make it difficult to develop a very flexible (ideally a la numpy) indexing system. In the end I instantiated `R 3` and `R 4` in a class `XYZ` with functions `getX`, `getY` etc, this was workable.

One function that I missed was `inv`, it would be nice if that was available in `Numeric.LinearAlgebra.Static` as well.

A thing that was a bit unfortunate, and hurt my productivity with the library a bit, is that I couldn't use it with `stack ghci` - I got a lot of errors which seemed to relate to the interface with the C code. `stack ghci` is experimental so it's quite understandable there are some problems here, but at a number of times I wished I could just pop into ghci with it and test some functions I had written. If you want I could file an issue for this with more detailed error messages, I don't know if `stack ghci` does work with hmatrix for you.

Thanks and cheers,
Sam

**Comment by albertoruiz** [comment]
Hi Sam,
Thank you very much for sharing your experiences.

I agree that in many cases the complexity of static checking is not worth the gain. The errors usually appear the first time we run the program, or by testing functions step by step in ghci. In fact, most of my code uses the regular interface and I have seldom suffered run-time dimension errors which are difficult to debug. And there are also more serious problems in linear algebra, like badly conditioned linear systems, etc. A practical approach is to write first a quick prototype with dynamic checking. 

In any case, it is fantastic that the compiler can verify that a given piece of code for array manipulation is (at least) "structurally" correct. When the type literals extension was available in ghc I wanted to experiment with this, it was a fun way for me to learn something about these advanced features. Of course the module can be improved in many ways.

Concerning the missing functions, there is no problem to add `inv`, although it actually has a very simple definition if we are sure the argument is non singular:

    inv = fromJust . flip linSolve eye
    
    λ> let m = matrix [1,2,5,5] :: L 2 2
    λ> m
    (matrix
     [ 1.0, 2.0
     , 5.0, 5.0 ] :: L 2 2)
    λ> let im = inv m
    λ> im
    (matrix
     [ -1.0,  0.4
     ,  1.0, -0.2 ] :: L 2 2)
    λ> m <> im
    (matrix
     [ 1.0, 0.0
     , 0.0, 1.0 ] :: L 2 2)

In general it is better to return a Maybe, `fromJust` produces an uninformative error message:

    λ> inv $ diag (vec3 1 1 0)
    *** Exception: Maybe.fromJust: Nothing

In relation to the indexing functions, your XYZ class is very practical. A possible alternative for general element access could be the following:

    data X (n :: Nat) = X

    acc :: forall n k . (Dim n, Dim k, k+1<=n) => R n -> X k -> ℝ
    acc v x = unwrap v LA.! pos
      where
        pos = fromIntegral . natVal $ (undefined :: Proxy k) :: Int
    
    λ> let v = vec3 1 2 3
    λ> acc v (X::X 0)
    1.0
    λ> acc v (X::X 1)
    2.0
    λ> acc v (X::X 2)
    3.0
    λ> acc v (X::X 3)

    <interactive>:91:1:
        Couldn't match type ‘'False’ with ‘'True’
        Expected type: 'True
          Actual type: (3 + 1) <=? 3
        In the expression: acc v (X :: X 3)
        In an equation for ‘it’: it = acc v (X :: X 3)

    getZ v = acc v (X::X 2)
    ... etc...

The dynamic interface has more powerful tools for data extraction, slices, etc., specially in the last version, but in the static interface we cannot use values. Perhaps something like this can be helpful...

Finally, I work with ghci and hmatrix everyday without any problem. But I do not yet use stack, sorry.
If you have a "clean" ghc-7.10 installation, just running something like

    cabal update
    sudo apt-get install libatlas-base-dev
    cabal install hmatrix

should work. If ghci fails in this simple case please let me know!

Sorry for the long message and thanks again!
Alberto

**Comment by samvher** [comment]
Thank you for your (again) informative response.

Importing hmatrix in ghci the way you suggest works. It's just that then I don't have access to the packages installed locally by stack, so it's not really a solution. But stack still has to mature a bit more so I guess that's the price I pay for using a young package :)

Best,
Sam
